import  pygame


head_right = pygame.image.load('snake_graphics/Graphics/head_right.png')
head_left = pygame.image.load('snake_graphics/Graphics/head_left.png')
head_down = pygame.image.load('snake_graphics/Graphics/head_down.png')
head_up = pygame.image.load('snake_graphics/Graphics/head_up.png')
tail_left = pygame.image.load('snake_graphics/Graphics/tail_left.png')
tail_right = pygame.image.load('snake_graphics/Graphics/tail_right.png')
tail_down = pygame.image.load('snake_graphics/Graphics/tail_down.png')
tail_up = pygame.image.load('snake_graphics/Graphics/tail_up.png')
snake_body_left_down = pygame.image.load('snake_graphics/Graphics/body_bottomright.png')
snake_body_right_down = pygame.image.load('snake_graphics/Graphics/body_bottomleft.png')
snake_body_left_up = pygame.image.load('snake_graphics/Graphics/body_topright.png')
snake_body_right_up = pygame.image.load('snake_graphics/Graphics/body_topleft.png')
snake_body_horizontal = pygame.image.load('snake_graphics/Graphics/body_horizontal.png')
snake_body_vertical = pygame.image.load('snake_graphics/Graphics/body_vertical.png')
apple = pygame.image.load('snake_graphics/Graphics/apple.png')
banana = pygame.image.load('snake_graphics/Graphics/banana1.png')
banana = pygame.transform.scale(banana, (30, 30))
background = pygame.image.load('snake_graphics/Graphics/background.jpg')
background = pygame.transform.scale(background, (600, 600))
black_box = pygame.image.load('snake_graphics/Graphics/blackbox.png')
black_box = pygame.transform.scale(black_box , (600,50))
bomb = pygame.image.load('snake_graphics/Graphics/bomb.png')
bomb = pygame.transform.scale(bomb , (30,30))
heart = pygame.image.load('snake_graphics/Graphics/heart pixel art 48x48.png')
heart = pygame.transform.scale(heart, (30, 30))
# x = pygame.image.load("snake_graphics/Graphics/")